name: EL8 OpenSSL 1.x Test

on:
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test-el8-openssl1:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:8
    
    name: Build and test on EL8 (OpenSSL 1.1.1)

    steps:
    - name: Install dependencies
      run: |
        dnf install -y epel-release
        dnf install -y gcc-c++ cmake3 openssl-devel libcurl-devel sqlite-devel libuuid-devel make git python3
        
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Check OpenSSL version
      run: |
        openssl version
        echo "Expected: OpenSSL 1.1.1 for EL8"
        
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: mkdir -p build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake3 -S . -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSCITOKENS_BUILD_UNITTESTS=ON -DSCITOKENS_EXTERNAL_GTEST=NO

    - name: Build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake3 --build build --config $BUILD_TYPE

    - name: Test
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: cd build && ctest -C $BUILD_TYPE --verbose
